### ISSUE TITLE
implement additional change types?

### ISSUE THREAD

**Issue by smnorris** [bcgov/FIT_changedetector#11]
Are any of these required?
```
{
    "MODIFIED_ALL": []
    "ALL_CHANGES": []
    "MODIFIED_BOTH_OBSLT": []
    "MODIFIED_ATTR_OBSLT": []
    "MODIFIED_GEOM_OBSLT": []
}
```
- "modified all" and "all_changes" and can be determined by combining the other outputs
- because diff requires primary keys to function, the `_OBSLT` keys are presumably redundant (values will always be equivalent to corresponding `MODIFIED_<>` keys)

**Comment by andershopperstead** [comment]
Thanks for this question. Joy, Jed and I discussed this today and none of these are required.
