### ISSUE TITLE
log summary to a file adjacent to output .gdb

### ISSUE THREAD

**Issue by smnorris** [bcgov/FIT_changedetector#15]
Log the following:
- input filenames
- output filename
- number of records in the various layers produced by the analysis

Write this to file, with filename having the same timestamp suffix as the output .gdb

**Comment by smnorris** [comment]
Rather than explicitly creating a summary file, I'd consider noting each of these items with the logger, and defaulting to redirecting the log to file.

**Comment by andershopperstead** [comment]
A log written to a file works great.
