### ISSUE TITLE
Geodatabase comparison: Only .gdb and .shp are supported

### ISSUE THREAD

**Issue by andershopperstead** [bcgov/FIT_changedetector#34]
Thanks for fixing the issue with multi-type shapefiles. I just found a new issue: 
After removing the duplicate primary keys, I tried to compare the Prince George data again. This error occurred:

Start Time: December 2, 2024 1:45:25 PM
2024-12-02 13:45:30,060 - root - INFO - Script tool parameters: {'debug': False,
 'drop_null_geometry': True,
 'dump_inputs': False,
 'fields': [],
 'hash_fields': [],
 'hash_key': 'fcd_hash_id',
 'ignore_fields': [],
 'new_fc': 'W:\\ilmb\\dss\\dss_workarea\\_contractors\\sinorris\\FIT_changedetector\\tests\\test_2024_11_29_PrinceGeorge\\013dacc1-f5fa-4b08-9fc9-e5f9fe7d181d.gdb\\Road_new',
 'original_fc': 'W:\\ilmb\\dss\\dss_workarea\\_contractors\\sinorris\\FIT_changedetector\\tests\\test_2024_11_29_PrinceGeorge\\d826ef7c-b852-4b2d-b7e8-fcb67aaa52de.gdb\\Road_original',
 'out_folder': 'W:\\ilmb\\dss\\dss_workarea\\_contractors\\sinorris\\FIT_changedetector\\tests\\test_2024_11_29_PrinceGeorge',
 'precision': 1.0,
 'primary_key': ['AssetID'],
 'suffix_a': 'original',
 'suffix_b': 'new'}
2024-12-02 13:45:30,061 - root - INFO - Output file: W:\ilmb\dss\dss_workarea\_contractors\sinorris\FIT_changedetector\tests\test_2024_11_29_PrinceGeorge\changedetector_20241202_1345.gdb
Only .gdb and .shp are supported
Only .gdb and .shp are supported
'original_file'
Failed script changedetector...
Failed to execute (changedetector).
Failed at December 2, 2024 1:45:31 PM (Elapsed Time: 5.63 seconds)

**Comment by smnorris** [comment]
My ad hoc detection of `gdb` vs `shp` isn't working, maybe I should use an arcpy method.

**Comment by smnorris** [comment]
Fixed, but the sample data still has issues:
```
2024-12-02 14:07:40,186:ERROR:fit_changedetector.cli: Field types do not match. Enabled: (int16, float64)```

**Comment by smnorris** [comment]
I'm not sure how to resolve the type mismatches - I could see this being fairly common when data comes from variable sources. 

Leave it up to the user to compare data types and fix?
Add an option to cast all integer types to float types?
