### ISSUE TITLE
test for arcgis dependent portion of script

### ISSUE THREAD

**Issue by smnorris** [bcgov/FIT_changedetector#35]
To catch issues like #34 somewhat automatically, add tests that check `arcgis.py`

Depends on an ESRI licence, but `pytest` has methods for skipping tests on given platforms https://docs.pytest.org/en/stable/how-to/skipping.html

**Comment by smnorris** [comment]
Not immediately sure how to handle passing test data to `arcpy.GetParameter()`, so I'll put this to the side for now - there is very little to be tested in this script beyond the `gdb`/`shp` detection

**Comment by smnorris** [comment]
It isn't an issue - I just missed spelling out / pasting a property of the path. 

Detection of input file type could be removed entirely if the tool's parameters matched the script's parameters (ie path to data, name of layer rather than an arcpy feature class), but the interface isn't as nice then.

**Comment by andershopperstead** [comment]
Understood. It would be nice to conserve the current concise interface if possible. Let me know when/if the code is stable enough to restart testing. Thank you!

**Comment by smnorris** [comment]
No issues to resume testing.
